name: build-on-tag
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: docker build -f ue-docker-app/Dockerfile ue-docker-app
